### PR TITLE
compile

### PR DESCRIPTION
**Pull request by F3rn4nd080**
How can contact any of the developers? please need help my telegram @F3rn4nd080

### CODE REVIEW

**Comment by F3rn4nd080** [comment]
> 
> 
> @FloridaStream yes. Discord `FloridaStream#0309`

not in discord, can you help me to compile? my telegram @F3rn4nd080

**Comment by FloridaStream** [comment]
@F3rn4nd080 this project is dead after VMP, please, forget him.

**Comment by F3rn4nd080** [comment]
VMP what meens? Sorry im a noob :D FloridaStream you have knowledge decrypting video streaming? i need a developer for a local stream service, nothing famous only for personal purpouse, talk to telegram i can find u in discord
my telegram @F3rn4nd080 

    El jueves, 14 de noviembre de 2019 1:16:22 p. m. GMT-3, FloridaStream <notifications@github.com> escribió:  
 
 
@F3rn4nd080 this project is dead after VMP, please, forget him.

**Comment by MythodeaLoL** [comment]
Never will work again. Let this die.

**Comment by kokarare1212** [comment]
I get the error message "License update not successful (no keys)"
It is probably because the version of widevinecdm is too old
However, when I change to a new version of widevinecdm.dll, I get an "OpenDrmSystem failed" error message.
It was exactly the same as I checked the dependency with dumpbin
I feel I need to update the version of inputstream.adaptive
It looks like you're modifying the original file
Please support with a new version

**Comment by kokarare1212** [comment]
I didn't succeed
This may be because w\*dev\*ne cdm is old
The library cannot be read when I try to run it with the latest version of w\*dev\*necdm
Or is it due to old inputstream.adaptive?
```
File : video_video
Info path : C:\Users\user\video_decrypter\tmp\_info\video
Decrypted path : C:\User\user\video_decrypter\tmp\_decrypted
Initialisation...
Successfully parsed .mpd file. #Streams: 2
Entering encryption section
CDMMessage: 1 arrived!
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1796  100    22  100  1774     22   1774  0:00:01 --:--:--  0:00:01  4605
License update not successful (no keys)
Initialize failed (SingleSampleDecrypter)
```

**Pull request merged**
